server:
  port: 8080

#spring:
#  security:
#    user:
#      name: fanyao
#      password: 666

spring:
  profiles:
    active: dev

  datasource:
    url: jdbc:mysql:///security?characterEncoding=utf8&serverTimezone=GMT%2B8&useSSL=false&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true
    username: root
    password: root




# 配置mybatis-plus
mybatis-plus:
  # 配置扫描xml
  mapper-locations:
    - classpath*:mapper/*Mapper.xml
  # 实体扫描，多个package用逗号或者分号分隔
  type-aliases-package: com.fanyao.spring.security.model
  #    显示sql
  #  configuration:
  #    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  #    log-prefix: mybatis.plus.sql
  global-config:
    db-config:
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)